# For prod profile
# CREATE DATABASE db_prod_blog_241 CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb  # http://localhost:8080//h2-console/
    username: sa
    password: password
  jpa:
    open-in-view: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create

logging:
  level:
    root: info
    com.kangmin: info
  file:
    name: log/spring-mvc-blog_prod.log

#server:
#  port: 8081

application:
  env:
    node: PROD

#
# Amazon Web Service
# such as SimpleEmailService
#
aws:
  access:
    key: ${AWS_ACCESS_KEY}
  secret:
    key: ${AWS_SECRET_KEY}
  s3:
    region: ${PROD_AWS_S3_REGION}
    bucket: ${PROD_AWS_S3_BUCKET}
