# For prod profile
# CREATE DATABASE db_prod_blog_241 CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_prod_mvc_blog?&useUnicode=true&character_set_server=utf8mb4&character_set_client=utf8mb4&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${PROD_MYSQL_DB_USERNAME}
    password: ${PROD_MYSQL_DB_PASSWORD}
  jpa:
    open-in-view: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update

logging:
  level:
    root: info
    com.kangmin: info
  file:
    name: log/spring-mvc-blog_prod.log

#server:
#  port: 8081

application:
  env:
    node: PROD

#
# Amazon Web Service
# such as SimpleEmailService
#
aws:
  access:
    key: ${AWS_ACCESS_KEY}
  secret:
    key: ${AWS_SECRET_KEY}
  s3:
    region: ${PROD_AWS_S3_REGION}
    bucket: ${PROD_AWS_S3_BUCKET}
